version: '3'
services:
  grpc-server:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rake grpc_server
    volumes:
      - .:/app
  grpc-client:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec rake grpc_client
    volumes:
      - .:/app
