# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: grpc_ex.proto for package ''

require "grpc"
require "grpc_ex/grpc_ex_pb"

module GrpcEx
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = "GrpcEx"

    rpc :Publish, PublishRequest, PublishResponse
    rpc :Consume, ConsumeRequest, stream(Message)
    rpc :Ack, AckRequest, AckResponse
    rpc :Ping, PingRequest, PingResponse
    rpc :Unsubscribe, UnsubscribeRequest, UnsubscribeResponse
  end

  Stub = Service.rpc_stub_class
end
